AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  comprehend-api

  SAM Template for comprehend-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  DynamoDBTableName:
    Description: DynamoDB Table Name
    Type: String
    ConstraintDescription: DynamoDB Table Name
    Default: comprehend-api-table

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - 
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Ref DynamoDBTableName

  GetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: comprehend_api/
      Handler: get.lambda_handler
      Runtime: python3.7
      Policies: 
        - ComprehendFullAccess
        - AmazonDynamoDBFullAccess
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /comprehend-api
            Method: get

  PostFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: comprehend_api/
      Handler: post.lambda_handler
      Runtime: python3.7
      Policies: 
        - ComprehendFullAccess
        - AmazonDynamoDBFullAccess
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /comprehend-api
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for GET function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
    
  GetFunction:
    Description: "GET Lambda Function ARN"
    Value: !GetAtt GetFunction.Arn
    
  GetFunctionIamRole:
    Description: "Implicit IAM Role created for GET function"
    Value: !GetAtt GetFunctionRole.Arn

  PostFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for POST function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/comprehend-api/"
    
  PostFunction:
    Description: "POST Lambda Function ARN"
    Value: !GetAtt PostFunction.Arn
    
  PostFunctionIamRole:
    Description: "Implicit IAM Role created for POST function"
    Value: !GetAtt PostFunctionRole.Arn
    